In [2]:
from google.colab import files

uploaded = files.upload()

Saving Telco_customer_churn.xlsx to Telco_customer_churn.xlsx

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import classification_report,confusion_matrix,ConfusionMatrixDisplay

In [5]:
df = pd.read_excel("Telco_customer_churn.xlsx")
df.head()

   CustomerID  Count  ...  CLTV                   Churn Reason
0  3668-QPYBK      1  ...  3239   Competitor made better offer
1  9237-HQITU      1  ...  2701                          Moved
2  9305-CDSKC      1  ...  5372                          Moved
3  7892-POOKP      1  ...  5003                          Moved
4  0280-XJGEX      1  ...  5340  Competitor had better devices

[5 rows x 33 columns]

In [6]:
df.shape

(7043, 33)

In [7]:
print(df.columns)

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

In [8]:
print(df['Churn Value'].value_counts())

Churn Value
0    5174
1    1869
Name: count, dtype: int64

In [9]:
drop_cols = [
    "CustomerID",
    "Count",
    "Country",
    "State",
    "City",
    "Zip Code",
    "Lat Long",
    "Latitude",
    "Longitude",
    "Lat Long",
    "Churn Score",
    "Churn Reason",
    "Churn Label"
]

In [10]:
df = df.drop(drop_cols,axis = 1)
df.head()

   Gender Senior Citizen Partner  ... Total Charges  Churn Value  CLTV
0    Male             No      No  ...        108.15            1  3239
1  Female             No      No  ...        151.65            1  2701
2  Female             No      No  ...         820.5            1  5372
3  Female             No     Yes  ...       3046.05            1  5003
4    Male             No      No  ...        5036.3            1  5340

[5 rows x 21 columns]

In [13]:
print(df['Gender'].unique())
print(df['Senior Citizen'].unique())
print(df['Partner'].unique())
print(df['Dependents'].unique())
print(df['Phone Service'].unique())
print(df['Multiple Lines'].unique())
print(df['Internet Service'].unique())
print(df['Online Security'].unique())
print(df['Online Backup'].unique())
print(df['Device Protection'].unique())
print(df['Tech Support'].unique())
print(df['Streaming TV'].unique())
print(df['Streaming Movies'].unique())
print(df['Contract'].unique())
print(df['Paperless Billing'].unique())
print(df['Payment Method'].unique())

['Male' 'Female']
['No' 'Yes']
['No' 'Yes']
['No' 'Yes']
['Yes' 'No']
['No' 'Yes' 'No phone service']
['DSL' 'Fiber optic' 'No']
['Yes' 'No' 'No internet service']
['Yes' 'No' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
['Month-to-month' 'Two year' 'One year']
['Yes' 'No']
['Mailed check' 'Electronic check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [15]:
l = LabelEncoder()
df['Gender'] = l.fit_transform(df['Gender'])
df['Senior Citizen'] = l.fit_transform(df['Senior Citizen'])
df['Partner'] = l.fit_transform(df['Partner'])
df['Dependents'] = l.fit_transform(df['Dependents'])
df['Phone Service'] = l.fit_transform(df['Phone Service'])
df['Multiple Lines'] = l.fit_transform(df['Multiple Lines'])
df['Internet Service'] = l.fit_transform(df['Internet Service'])
df['Online Security'] = l.fit_transform(df['Online Security'])
df['Online Backup'] = l.fit_transform(df['Online Backup'])
df['Device Protection'] = l.fit_transform(df['Device Protection'])
df['Tech Support'] = l.fit_transform(df['Tech Support'])
df['Streaming TV'] = l.fit_transform(df['Streaming TV'])
df['Streaming Movies'] = l.fit_transform(df['Streaming Movies'])
df['Contract'] = l.fit_transform(df['Contract'])
df['Paperless Billing'] = l.fit_transform(df['Paperless Billing'])

In [16]:
df.head()

   Gender  Senior Citizen  Partner  ...  Total Charges  Churn Value  CLTV
0       1               0        0  ...         108.15            1  3239
1       0               0        0  ...         151.65            1  2701
2       0               0        0  ...          820.5            1  5372
3       0               0        1  ...        3046.05            1  5003
4       1               0        0  ...         5036.3            1  5340

[5 rows x 21 columns]

In [17]:
df = pd.get_dummies(df,columns=['Payment Method'],dtype="int64")
df.head()

   Gender  ...  Payment Method_Mailed check
0       1  ...                            1
1       0  ...                            0
2       0  ...                            0
3       0  ...                            0
4       1  ...                            0

[5 rows x 24 columns]

In [20]:
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
df.dropna(inplace=True)
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

Gender                                         1.0000
Senior Citizen                                 0.0000
Partner                                        1.0000
Dependents                                     0.0000
Tenure Months                                 46.0000
Phone Service                                  0.0000
Multiple Lines                                 2.0000
Internet Service                               1.0000
Online Security                                2.0000
Online Backup                                  2.0000
Device Protection                              2.0000
Tech Support                                   2.0000
Streaming TV                                   2.0000
Streaming Movies                               2.0000
Contract                                       1.0000
Paperless Billing                              1.0000
Monthly Charges                               54.2750
Total Charges                               3393.2875
Churn Value                                    1.0000
CLTV                                        1911.2500
Payment Method_Bank transfer (automatic)       0.0000
Payment Method_Credit card (automatic)         0.0000
Payment Method_Electronic check                1.0000
Payment Method_Mailed check                    0.0000
dtype: float64

In [21]:
outliers = (df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))
print(outliers.sum())

Gender                                         0
Senior Citizen                              1142
Partner                                        0
Dependents                                  1620
Tenure Months                                  0
Phone Service                                680
Multiple Lines                                 0
Internet Service                               0
Online Security                                0
Online Backup                                  0
Device Protection                              0
Tech Support                                   0
Streaming TV                                   0
Streaming Movies                               0
Contract                                       0
Paperless Billing                              0
Monthly Charges                                0
Total Charges                                  0
Churn Value                                    0
CLTV                                           0
Payment Method_Bank transfer (automatic)    1542
Payment Method_Credit card (automatic)      1521
Payment Method_Electronic check                0
Payment Method_Mailed check                 1604
dtype: int64

In [22]:
df = df[~outliers.any(axis=1)]
df.shape

(1318, 24)

In [28]:
df.head()

    Gender  ...  Payment Method_Mailed check
32       1  ...                            0
34       0  ...                            0
35       1  ...                            0
60       0  ...                            0
69       1  ...                            0

[5 rows x 24 columns]

In [29]:
x = df.drop('Churn Value',axis = 1)
y = df['Churn Value']

In [30]:
ss = StandardScaler()
x['Tenure Months'] = ss.fit_transform(x['Tenure Months'].values.reshape(-1,1))
x['Monthly Charges'] = ss.fit_transform(x['Monthly Charges'].values.reshape(-1,1))
x['Total Charges'] = ss.fit_transform(x['Total Charges'].values.reshape(-1,1))
x['CLTV'] = ss.fit_transform(x['CLTV'].values.reshape(-1,1))
x.head()

    Gender  ...  Payment Method_Mailed check
32       1  ...                            0
34       0  ...                            0
35       1  ...                            0
60       0  ...                            0
69       1  ...                            0

[5 rows x 23 columns]

In [31]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [50]:
lr = LogisticRegression(max_iter=1000)
lr.fit(x_train,y_train)
lr_pred = lr.predict(x_test)
print(lr.score(x_train,y_train))
print(lr.score(x_test,y_test))
print(classification_report(y_test,lr_pred))

0.7058823529411765
0.6666666666666666
              precision    recall  f1-score   support

           0       0.72      0.57      0.63       134
           1       0.63      0.77      0.69       130

    accuracy                           0.67       264
   macro avg       0.67      0.67      0.66       264
weighted avg       0.68      0.67      0.66       264

In [51]:
rf = RandomForestClassifier(n_estimators=500,random_state=42,n_jobs=-1,class_weight="balanced",max_depth = 8,min_samples_leaf=2)
rf.fit(x_train,y_train)
rf_pred = rf.predict(x_test)
print(rf.score(x_train,y_train))
print(rf.score(x_test,y_test))
print(classification_report(y_test,rf_pred))

0.8510436432637571
0.6477272727272727
              precision    recall  f1-score   support

           0       0.69      0.55      0.61       134
           1       0.62      0.75      0.68       130

    accuracy                           0.65       264
   macro avg       0.65      0.65      0.65       264
weighted avg       0.66      0.65      0.64       264

In [52]:
gbc = GradientBoostingClassifier(n_estimators=200,random_state=42,max_depth=3,min_samples_leaf=5,learning_rate=0.05)
gbc.fit(x_train,y_train)
gbc_pred = gbc.predict(x_test)
print(gbc.score(x_train,y_train))
print(gbc.score(x_test,y_test))
print(classification_report(y_test,gbc_pred))

0.8358633776091081
0.6363636363636364
              precision    recall  f1-score   support

           0       0.66      0.58      0.62       134
           1       0.62      0.69      0.65       130

    accuracy                           0.64       264
   macro avg       0.64      0.64      0.64       264
weighted avg       0.64      0.64      0.64       264

In [53]:
xgb_model = XGBClassifier(
        n_estimators=300,
        learning_rate=0.03,
        max_depth=3,
        min_child_weight=3,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=2,
        random_state=42,
        eval_metric="logloss"
        )

xgb_model.fit(x_train, y_train)

xgb_pred = xgb_model.predict(x_test)

print(xgb_model.score(x_train, y_train))
print(xgb_model.score(x_test, y_test))
print(classification_report(y_test, xgb_pred))

0.786527514231499
0.6401515151515151
              precision    recall  f1-score   support

           0       0.66      0.59      0.62       134
           1       0.62      0.69      0.65       130

    accuracy                           0.64       264
   macro avg       0.64      0.64      0.64       264
weighted avg       0.64      0.64      0.64       264

In [54]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

models = {
    "Logistic Regression": lr,
    "Random Forest": rf,
    "Gradient Boosting": gbc,
    "XGBoost": xgb_model
}



for name, model in models.items():

    pred = model.predict(x_test)

    print(name)
    print("Accuracy:", accuracy_score(y_test, pred))
    print("Precision:", precision_score(y_test, pred))
    print("Recall:", recall_score(y_test, pred))
    print("F1 Score:", f1_score(y_test, pred))
    print("ROC AUC Score:", roc_auc_score(y_test, pred))
    print('-'*30)

Logistic Regression
Accuracy: 0.6666666666666666
Precision: 0.6329113924050633
Recall: 0.7692307692307693
F1 Score: 0.6944444444444444
ROC AUC Score: 0.6681974741676234
------------------------------
Random Forest
Accuracy: 0.6477272727272727
Precision: 0.6178343949044586
Recall: 0.7461538461538462
F1 Score: 0.6759581881533101
ROC AUC Score: 0.6491963260619977
------------------------------
Gradient Boosting
Accuracy: 0.6363636363636364
Precision: 0.6164383561643836
Recall: 0.6923076923076923
F1 Score: 0.6521739130434783
ROC AUC Score: 0.6371986222732492
------------------------------
XGBoost
Accuracy: 0.6401515151515151
Precision: 0.6206896551724138
Recall: 0.6923076923076923
F1 Score: 0.6545454545454545
ROC AUC Score: 0.6409299655568312
------------------------------

In [59]:
xgb_new = XGBClassifier(
        n_estimators=150,
        learning_rate=0.02,

        max_depth=2,
        min_child_weight=12,

        gamma=0.5,

        subsample=0.65,
        colsample_bytree=0.65,

        reg_alpha=1.0,
        reg_lambda=8.0,

        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42
)

xgb_new.fit(x_train, y_train)

xgb_new_pred = xgb_new.predict(x_test)

In [60]:
print(xgb_new.score(x_train, y_train))
print(xgb_new.score(x_test, y_test))
print(classification_report(y_test, xgb_new_pred))

0.7352941176470589
0.6363636363636364
              precision    recall  f1-score   support

           0       0.68      0.54      0.60       134
           1       0.61      0.73      0.66       130

    accuracy                           0.64       264
   macro avg       0.64      0.64      0.63       264
weighted avg       0.64      0.64      0.63       264

In [61]:
param_grid = {
    "model__n_estimators": [100, 150, 200, 300, 400],
    "model__learning_rate": [0.01, 0.02, 0.03, 0.05, 0.08],

    "model__max_depth": [2, 3, 4],
    "model__min_child_weight": [3, 5, 8, 10, 15],

    "model__gamma": [0, 0.1, 0.3, 0.5, 1],

    "model__subsample": [0.6, 0.7, 0.8, 0.9],
    "model__colsample_bytree": [0.6, 0.7, 0.8, 0.9],

    "model__reg_alpha": [0, 0.1, 0.3, 0.5, 1],
    "model__reg_lambda": [2, 3, 5, 8, 10]
}
from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=param_grid,
    n_iter=40,
    scoring="f1",
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

random_search.fit(x_train, y_train)
print("Best Parameters:")
print(random_search.best_params_)

print("\nBest CV F1:")
print(random_search.best_score_)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
Best Parameters:
{'model__subsample': 0.8, 'model__reg_lambda': 10, 'model__reg_alpha': 0.3, 'model__n_estimators': 400, 'model__min_child_weight': 10, 'model__max_depth': 2, 'model__learning_rate': 0.02, 'model__gamma': 0.5, 'model__colsample_bytree': 0.6}

Best CV F1:
0.6991455742288151

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [12:56:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "model__colsample_bytree", "model__gamma", "model__learning_rate", "model__max_depth", "model__min_child_weight", "model__n_estimators", "model__reg_alpha", "model__reg_lambda", "model__subsample" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [62]:
best_xgb = random_search.best_estimator_
best_xgb.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [12:58:14] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "model__colsample_bytree", "model__gamma", "model__learning_rate", "model__max_depth", "model__min_child_weight", "model__n_estimators", "model__reg_alpha", "model__reg_lambda", "model__subsample" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=3, missing=nan, model__colsample_bytree=0.6,
              model__gamma=0.5, model__learning_rate=0.02, model__max_depth=2,
              model__min_child_weight=10, ...)

In [63]:
y_pred = best_xgb.predict(x_test)
y_prob = best_xgb.predict_proba(x_test)[:, 1]

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1       :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy : 0.6401515151515151
Precision: 0.6206896551724138
Recall   : 0.6923076923076923
F1       : 0.6545454545454545
ROC-AUC  : 0.7204936854190586

Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.59      0.62       134
           1       0.62      0.69      0.65       130

    accuracy                           0.64       264
   macro avg       0.64      0.64      0.64       264
weighted avg       0.64      0.64      0.64       264