In [14]:
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
import pandas as pd
df = pd.read_csv("salaries.csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [11]:
inputs = df.drop("salary_more_then_100k", axis = "columns" )
target = df["salary_more_then_100k"]
inputs.head()

  company                  job     degree
0  google      sales executive  bachelors
1  google      sales executive    masters
2  google     business manager  bachelors
3  google     business manager    masters
4  google  computer programmer  bachelors

In [12]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

inputs["company_n"] = le_company.fit_transform(inputs['company'])
inputs["Job_n"] = le_job.fit_transform(inputs['job'])
inputs["degree_n"] = le_degree.fit_transform(inputs['degree'])
inputs.head()

  company                  job     degree  company_n  Job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [24]:
inputs_n = inputs.drop(['company','job','degree'],axis='columns')
final_df = pd.concat([inputs_n,target],axis = 1)
final_df.head()

   company_n  Job_n  degree_n  salary_more_then_100k
0          2      2         0                      0
1          2      2         1                      0
2          2      0         0                      1
3          2      0         1                      1
4          2      1         0                      0

In [25]:
model = tree.DecisionTreeClassifier()
y_pred = model.fit(inputs_n,target)
y_pred

DecisionTreeClassifier()

In [26]:
y_pred.predict([[2,2,1]])

C:\Users\Shibam\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [27]:
model.score(inputs_n,target)

1.0

In [ ]:
#Ecercise

In [60]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression, LogisticRegression

In [61]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [62]:
inputs = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked','Survived'],axis = 'columns')
target = df['Survived']
inputs.head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [63]:
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [69]:
inputs['Fare'] = inputs['Fare'].fillna(0).astype(int)
inputs['Age'] = inputs['Age'].fillna(0).astype(int)
le_Sex = LabelEncoder()
inputs['Sex_n'] = le_Sex.fit_transform(inputs['Sex']) 
inputs_n = inputs.drop('Sex',axis = 'columns')
inputs_n.head()

   Pclass  Age  Fare  Sex_n
0       3   22     7      1
1       1   38    71      0
2       3   26     7      0
3       1   35    53      0
4       3   35     8      1

In [71]:
x_train,x_test,y_train,y_test = train_test_split(inputs_n,target,test_size = 0.2,random_state = 42)
model1 = LinearRegression()
model2 = LogisticRegression()
model1.fit(x_train,y_train)

LinearRegression()

In [72]:
model2.fit(x_train,y_train)

LogisticRegression()

In [75]:
model1.predict(x_test)

array([0.12693991, 0.23525938, 0.09593251, 0.79010584, 0.61878587,
       0.92562365, 0.63835542, 0.10422513, 0.61497325, 0.92428533,
       0.39079166, 0.06108172, 0.64235973, 0.08131865, 0.22861984,
       0.93156149, 0.38326227, 0.63835542, 0.24177231, 0.37595535,
       0.09008696, 0.38916934, 0.61058909, 0.09637743, 0.12671745,
       0.1149956 , 0.38062349, 0.23592677, 0.12376391, 0.59305247,
       0.09739389, 0.60620494, 0.43974629, 0.63835542, 0.09907774,
       0.08726004, 0.39993981, 0.63835542, 0.9093224 , 0.12516021,
       0.26388834, 0.08278004, 0.12538268, 0.12516021, 0.57415031,
       0.10778452, 0.09761635, 0.09199327, 0.09008696, 0.37345029,
       0.63371803, 0.89096456, 0.07115404, 0.44369263, 0.03017016,
       0.9375372 , 0.233798  , 0.92814648, 0.74505612, 0.61058909,
       0.09447112, 0.77676168, 0.75639813, 0.43863398, 0.12516021,
       0.71045856, 0.26388834, 0.08278004, 0.10031666, 0.88762763,
       0.7593209 , 0.97824774, 0.40175027, 0.90773795, 0.09154835,
       0.07433004, 0.59451385, 0.9250178 , 0.73889227, 0.58133062,
       0.10889683, 0.75137735, 0.91762213, 0.12516021, 0.35790871,
       0.34021471, 0.92610289, 0.91488395, 0.37753979, 0.12516021,
       0.11489975, 0.63054203, 0.35104671, 0.12516021, 0.12516021,
       0.08424142, 0.37449396, 0.05962033, 0.74181504, 0.08570281,
       0.34532778, 0.07401173, 0.93874535, 0.06962757, 0.08154111,
       0.08862558, 0.74175351, 0.37284088, 0.08176358, 0.38151334,
       0.95783566, 0.09593251, 0.96606675, 0.38624657, 0.48223653,
       0.09637743, 0.33687778, 0.22839738, 0.76583383, 0.57421539,
       0.24717293, 0.91641042, 0.87132993, 0.2847891 , 0.08862558,
       0.38770796, 0.8802213 , 0.41557368, 0.63991265, 0.09469358,
       0.63835542, 0.12693991, 0.27833771, 0.6321608 , 0.37392242,
       0.61799187, 0.97073845, 0.08278004, 0.06378203, 0.6142751 ,
       0.09469358, 0.73301596, 0.24031092, 0.23005046, 0.58625555,
       0.74896459, 0.23738815, 0.18411089, 0.97874709, 0.0625431 ,
       0.12538268, 0.09008696, 0.09885528, 0.64213727, 0.12538268,
       0.12516021, 0.13606085, 0.63835542, 0.74470705, 0.59337078,
       0.09154835, 0.43885645, 0.22423568, 0.96450952, 0.12538268,
       0.35165257, 0.24695046, 0.9576132 , 0.09300974, 0.07401173,
       0.41347568, 0.76811998, 0.38624657, 0.62698264, 0.10031666,
       0.12516021, 0.58816186, 0.76891398, 0.63451203])

In [76]:
model2.predict(x_test)

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1])

In [77]:
model1.score(x_test,y_test)

0.4175764218707324

In [79]:
model2.score(x_test,y_test)

0.776536312849162

In [80]:
model3 = tree.DecisionTreeClassifier()
model3.fit(x_train,y_train)
model3

DecisionTreeClassifier()

In [81]:
model3.predict(x_test)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0])

In [82]:
model3.score(x_test,y_test)

0.7821229050279329

In [83]:
final_df = pd.concat([inputs_n,target],axis = 1)
final_df.head()

   Pclass  Age  Fare  Sex_n  Survived
0       3   22     7      1         0
1       1   38    71      0         1
2       3   26     7      0         1
3       1   35    53      0         1
4       3   35     8      1         0

In [ ]:
model3.predict([[3,]])